<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerESq6vpB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerESq6vpB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerESq6vpB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerESq6vpB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerESq6vpB\App_KernelDevDebugContainer([
    'container.build_hash' => 'ESq6vpB',
    'container.build_id' => '614aebef',
    'container.build_time' => 1641219695,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerESq6vpB');
