<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL2gl1sx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL2gl1sx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL2gl1sx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL2gl1sx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL2gl1sx\App_KernelDevDebugContainer([
    'container.build_hash' => 'L2gl1sx',
    'container.build_id' => 'b971ebf2',
    'container.build_time' => 1641224924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL2gl1sx');
