<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3woC4b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3woC4b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ3woC4b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ3woC4b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ3woC4b\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z3woC4b',
    'container.build_id' => '258cc1b7',
    'container.build_time' => 1641296248,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3woC4b');
